import { type Metadata } from 'next'
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import './globals.css'
import Navbar from "@/components/Navbar"
import SyncUser from "@/components/SyncUser"
import ClerkModalFix from "@/components/ClerkModalFix"

export const metadata: Metadata = {
  title: 'OpenForge',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider 
      appearance={{
        baseTheme: dark,
        elements: {
          modal: {
            position: 'fixed !important',
            top: '0 !important',
            left: '0 !important',
            right: '0 !important',
            bottom: '0 !important',
            display: 'flex !important',
            alignItems: 'center !important',
            justifyContent: 'center !important',
            zIndex: '999999 !important',
            padding: '1rem !important',
            margin: '0 !important',
            maxHeight: '100vh !important',
            maxWidth: '100vw !important',
            transform: 'none !important'
          },
          modalCard: {
            position: 'relative !important',
            margin: '0 !important',
            transform: 'none !important',
            top: 'auto !important',
            left: 'auto !important',
            right: 'auto !important',
            bottom: 'auto !important',
            maxHeight: '90vh !important',
            overflowY: 'auto !important'
          }
        }
      }}
    >
      <html lang="en" className="dark">
        <head>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
          <link href="https://fonts.googleapis.com/css2?family=Hanken+Grotesk:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
        </head>
        <body className="antialiased hanken-grotesk" suppressHydrationWarning>
          <SyncUser />
          <Navbar />
          {children}
          <ClerkModalFix />
        </body>
      </html>
    </ClerkProvider>
  )
}
