import { type Metadata } from 'next'
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import './globals.css'
import Navbar from "@/components/Navbar"
import SyncUser from "@/components/SyncUser"

export const metadata: Metadata = {
  title: 'OpenForge',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider 
      appearance={{
        baseTheme: dark,
        elements: {
          modal: {
            maxHeight: '70vh',
            height: 'auto'
          },
          rootBox: 'clerk-custom'
        }
      }}
    >
      <html lang="en" className="dark">
        <body className="antialiased" suppressHydrationWarning>
          <SyncUser />
          <Navbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
